name: Go

on:
  - push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - name: go test
        env:
          TOKEN_INDEX: ${{ secrets.TOKEN_INDEX }}
          RPC_PROVIDER: ${{ secrets.RPC_PROVIDER }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BATCH_CONTRACT: ${{ secrets.BATCH_CONTRACT }}
        run: go test -v -covermode atomic -coverprofile=covprofile ./...
      - name: install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github